'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Minus, Plus, Pause, Play, SlidersHorizontal, Info, RotateCcw } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import type { Engine, Stage, ViewOptions } from '@/lib/terra/engine';
import type { EarthView } from '@/lib/terra/spatial';
import { currentVersion } from '@/lib/terra/releases';
import type { TransformationState } from '@/lib/terra/personal-contract';
import { connectWorldNavigator, publishWorldState, sendWorldCommand } from '@/lib/world/bridge';
import { WORLD_TARGETS, type GenesisState, type WorldState } from '@/lib/world/commands';
import specialStyles from './special-destinations.module.css';
import GlobeVoice from '@/components/terra-voice/GlobeVoice';
import integrationStyles from '@/components/terra-voice/globe-integration.module.css';

const initialOptions:ViewOptions={glow:1.15,shimmer:1.1,depth:true,threads:.55,density:.85,borders:false,motion:true};
export default function TerraExperience(){
 const host=useRef<HTMLDivElement>(null),markers=useRef<HTMLDivElement>(null),engine=useRef<Engine|null>(null);
 const [stage,setStage]=useState<Stage>('orbit'),[ready,setReady]=useState(false),[error,setError]=useState(''),[fatalError,setFatalError]=useState(false),[options,setOptions]=useState<ViewOptions>(initialOptions);
 const askGlobe = useRef<((question: string) => void) | null>(null);
 const connectAsk = useCallback((ask: ((question: string) => void) | null) => { askGlobe.current = ask; }, []);
 const [view,setView]=useState<EarthView>('globe'),[settling,setSettling]=useState(false);
 const [exploring,setExploring]=useState(false);
 const [transformation,setTransformation]=useState<TransformationState>({phase:'terra',progress:0,busy:false});
 const [genesis,setGenesis]=useState<GenesisState>({phase:'core',progress:0,busy:true});
 const [world,setWorld]=useState<WorldState|null>(null);
 const target=WORLD_TARGETS.find(t=>t.id===world?.targetId);
 const isMakkah=world?.targetId==='makkah';
 const previousStage=useRef<Stage>('orbit');const inCity=stage==='city';const flying=stage==='descending'||stage==='ascending';const approaching=flying&&world?.tier!=='planet';
 useEffect(()=>{const controller=new AbortController();let instance:Engine|undefined;let disconnectWorld:(()=>void)|undefined;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const opts={...initialOptions,motion:!reduced};
  import('@/lib/terra/engine').then(({createEarth})=>{if(controller.signal.aborted||!host.current||!markers.current)return;return createEarth(host.current,markers.current,{showStories:false,genesis:setGenesis,worldState:state=>{setWorld(state);publishWorldState(state);},transformation:setTransformation,ready:()=>setReady(true),stage:s=>{setSettling(s==='orbit'&&previousStage.current==='ascending');previousStage.current=s;setStage(s);setExploring(false);},view:setView,arrival:()=>setSettling(false),error:(message,fatal=false)=>{setError(message);setFatalError(fatal);if(fatal)setReady(false);},interact:()=>setExploring(true),coordinates:()=>{}},controller.signal);}).then(e=>{if(!e)return;if(controller.signal.aborted){e.dispose();return;}instance=e;engine.current=e;e.configure(opts);setOptions(opts);disconnectWorld=connectWorldNavigator(async command=>{if(command.type==='flyTo'||command.type==='flyToLocation'||command.type==='resetView'||command.type==='setScale'){setExploring(false);setSettling(false);}return e.command(command);},()=>e.worldState());setWorld(e.worldState());}).catch(e=>{if(e?.name!=='AbortError')setError('The star field could not open. Please try a browser with WebGL enabled, or reload to try again.');});
  return()=>{controller.abort();disconnectWorld?.();instance?.dispose();engine.current=null;};
 },[]);
 useEffect(()=>{if(stage!=='city')return;const timer=setTimeout(()=>setExploring(true),4500);return()=>clearTimeout(timer);},[stage]);
 function configure(partial:Partial<ViewOptions>){const next={...options,...partial};setOptions(next);engine.current?.configure(next);}
 return <main className={`${integrationStyles.integrationRoot} experience answering-mode stage-${stage} view-${view}${exploring?' is-exploring':''}${settling?' is-settling':''}${options.motion?'':' motion-paused'}${genesis.busy?' genesis-active':''}`} data-genesis={genesis.phase} data-scale={world?.tier??'planet'} data-target={world?.targetId??''} data-location={world?.location?.name??''} data-transformation={transformation.phase}>
  <header className="masthead"><span className="wordmark">TERRA <i aria-hidden="true">✦</i> ASTRA</span><span className="edition">ASK THE EARTH</span><Dialog><DialogTrigger asChild><button className="about-button" aria-label="About Terra Astra"><Info size={17}/><span>About</span></button></DialogTrigger><DialogContent className="about-dialog"><DialogTitle className="dialog-title">A world you can ask about.</DialogTitle><DialogDescription className="about-intro">Ask Astra to take you from the planet to a region, city or street across the stellar Earth.</DialogDescription><p>A dense stellar core becomes Earth. Follow its light through surface, atmosphere and orbit, then descend into Singapore, New York, Palm Jumeirah or Makkah.</p><p>Drag to orbit, zoom with the controls, or ask Astra where to go. Questions can be about any subject; the globe moves when a geographic view helps.</p><p>Try: “Research why Tokyo has frequent earthquakes in depth, with two independent perspectives and a diagram.”</p><div className="data-note"><h3>The light behind the world</h3><p>Geography: <a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a>. City light patterns: <a href="https://science.nasa.gov/earth/earth-observatory/earth-at-night/maps/" target="_blank" rel="noreferrer">NASA Black Marble, 2016</a>, artistically sampled from the historical composite. Light intensity does not represent population.</p><p>Terrain and ocean depth: <a href="https://www.ncei.noaa.gov/products/etopo-global-relief-model" target="_blank" rel="noreferrer">NOAA ETOPO 2022</a>. Street geometry: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a>, Singapore snapshot retrieved 9 September 2026; New York, Palm Jumeirah and Makkah snapshots retrieved 13 September 2026. Detailed exploration covers central Singapore and a curated lower-Manhattan neighbourhood. Dim surrounding city fields are impressionistic continuations, not surveyed roads. Palm and Makkah use bounded snapshots. Makkah’s collective flow is illustrative and does not represent measured crowd density.</p></div><a className="about-history-link" href="/history">Build history · v{currentVersion}</a></DialogContent></Dialog></header>
  <div ref={host} className="universe" />
  {genesis.busy&&ready?<button className="genesis-skip" onClick={()=>engine.current?.skipGenesis()}>Skip introduction</button>:null}
  <div ref={markers} className="map-markers" aria-hidden="true" />
  {!ready&&!error?<p className="loading-message" role="status">Gathering the constellations<span className="loading-dots">…</span></p>:null}
  {error?<div className="error-message" role="alert"><p>{error}</p><button onClick={()=>ready&&!fatalError?setError(''):location.reload()}>{fatalError?'Restart journey':ready?'Dismiss':'Try again'}</button></div>:null}
  <section className="opening" aria-live="polite" aria-hidden={settling||exploring||view!=='globe'}>
   <p className="eyebrow" hidden={inCity&&isMakkah}>{stage==='orbit'?'A WORLD YOU CAN ASK ABOUT':stage==='city'?'A CITY, ALIVE':!approaching?'PART OF SOMETHING LARGER':'A LITTLE CLOSER'}</p>
   {stage==='orbit'?<><h1>Where shall<br/><em>we go?</em></h1><p>Ask a question.<br/>Follow it across the world.</p></>:inCity&&isMakkah?<><h1>Makkah.<br/><em>Masjid al-Haram.</em></h1><p>Collective movement around the Kaaba.<br/>An interpretive flow, never live tracking.</p></>:inCity?<><h1>{target?.label??'Earth'},<br/><em>alive.</em></h1><p>Roads become rivers of light.<br/>Activity gathers, then drifts.</p></>:<><h1>{approaching?'Coming':'Going'}<br/><em>{approaching?'closer.':'beyond.'}</em></h1><p>{approaching?'A planet becomes a place.':'A city becomes part of the world.'}</p></>}
  </section>
  {inCity&&isMakkah?<p className={specialStyles.flowDisclosure}>Interpretive flow · No live tracking</p>:null}
  <div className="view-tools" aria-label="View controls">
   <button onClick={()=>location.reload()} aria-label="Restart journey" title="Restart journey"><RotateCcw size={17}/></button>
   <button disabled={!ready||flying||transformation.busy||genesis.busy} onClick={()=>engine.current?.zoom(.80)} aria-label="Zoom in" title="Zoom in"><Plus size={19}/></button><button disabled={!ready||flying||transformation.busy||genesis.busy} onClick={()=>engine.current?.zoom(1.25)} aria-label="Zoom out" title="Zoom out"><Minus size={19}/></button><span className="tool-divider"/>
   <button disabled={!ready} onClick={()=>configure({motion:!options.motion})} aria-label={options.motion?'Pause ambient motion':'Resume ambient motion'} title={options.motion?'Pause ambient motion':'Resume ambient motion'}>{options.motion?<Pause size={16}/>:<Play size={16}/>}</button>
   <Dialog><DialogTrigger asChild><button disabled={!ready} aria-label="Adjust the constellations" title="Adjust the constellations"><SlidersHorizontal size={18}/></button></DialogTrigger><DialogContent className="tuning-dialog"><DialogTitle className="dialog-title">Light, to your liking.</DialogTitle><DialogDescription>Find the balance between the stars and the space between them.</DialogDescription><div className="tuning-row"><label id="glow-label">Star glow</label><Slider ref={node=>{node?.querySelector('[role="slider"]')?.setAttribute('aria-labelledby','glow-label');}} aria-labelledby="glow-label" min={.25} max={2} step={.05} value={[options.glow]} onValueChange={([glow])=>configure({glow})}/></div><div className="tuning-row"><label id="shimmer-label">Star shimmer</label><Slider ref={node=>{node?.querySelector('[role="slider"]')?.setAttribute('aria-labelledby','shimmer-label');}} aria-labelledby="shimmer-label" min={0} max={2} step={.05} value={[options.shimmer]} onValueChange={([shimmer])=>configure({shimmer})}/></div><div className="tuning-row"><label id="threads-label">Constellation threads</label><Slider ref={node=>{node?.querySelector('[role="slider"]')?.setAttribute('aria-labelledby','threads-label');}} aria-labelledby="threads-label" min={0} max={1.4} step={.05} value={[options.threads]} onValueChange={([threads])=>configure({threads})}/></div><div className="tuning-row"><label id="density-label">Land star density</label><Slider ref={node=>{node?.querySelector('[role="slider"]')?.setAttribute('aria-labelledby','density-label');}} aria-labelledby="density-label" min={.2} max={1} step={.05} value={[options.density]} onValueChange={([density])=>configure({density})}/></div><div className="switch-row"><label htmlFor="borders">Trace country boundaries</label><Switch id="borders" checked={options.borders} onCheckedChange={borders=>configure({borders})}/></div><div className="switch-row"><label htmlFor="motion">Ambient motion</label><Switch id="motion" checked={options.motion} onCheckedChange={motion=>configure({motion})}/></div><button className="text-button" onClick={()=>configure({...initialOptions,motion:options.motion})}>Restore the original light</button></DialogContent></Dialog>
  </div>
  {ready&&!genesis.busy?<nav className="scale-navigation" aria-label="World scale">{(['planet','region','city','street'] as const).map(tier=><button key={tier} aria-current={world?.tier===tier?'step':undefined} disabled={!!world?.busy||(!world?.targetId&&tier!=='planet')||((world?.targetId==='challenger-deep'||world?.targetId==='location')&&(tier==='city'||tier==='street'))} onClick={()=>void sendWorldCommand({type:'setScale',tier})}>{tier}</button>)}</nav>:null}
  <GlobeVoice ready={ready&&!genesis.busy&&!transformation.busy} onAskReady={connectAsk}/>
  <footer className="credits"><span>Geography: Natural Earth / NOAA ETOPO <span className="credit-dot">·</span> Night lights: NASA, 2016</span><span className="credit-links"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a><a className="version-link" href="/history" aria-label={`Build history, version ${currentVersion}`}>v{currentVersion}</a></span></footer>
  <noscript><p className="error-message">Enable JavaScript to explore Terra Astra.</p></noscript>
 </main>;
}
