/** User-facing release history. Keep historical entries tied to their saved milestones. */
export const currentVersion = '0.8.0';

export const releases = [
  {
    version: '0.8.0', date: '2026-09-13', dateLabel: '13 September 2026', title: 'An explanation beside the Earth', milestone: 'This build',
    changes: [
      'Answers now have an editorial title, short lead and generated explanatory graphic beside the map. A slim bottom transcript separates your words from Astra’s, with one stop action.',
      'A data-only model planner composes simple three-dimensional shapes into starlight models within the existing globe. The camera settles into the horizon and gently orbits the focal scene.',
      'Phone layouts place the globe above a bounded answer panel and keep touch controls above the safe area. Manual movement and reduced motion remain respected.',
      'Voice handles late transcript fragments, microphone interruption and transient connection loss, with a playful Ripple voice. A local three-minute cutoff has been removed.',
      'Diagnostics record only bounded metadata in the browser and can be exported from the composer menu. Server rendering no longer initializes the recorder.',
    ],
    review: 'Automated checks cover the shared command boundary, model geometry, request limits, cancellation, voice lifecycle and telemetry. A real local answer generated a Borobudur model and diagram inside the map. Native browser checks cover desktop and phone-width layouts; physical-phone and microphone audio verification remain separate. Real-data adapters are prepared but are not yet connected to the visible movement layers.',
  },
  {
    version: '0.7.2', date: '2026-09-13', dateLabel: '13 September 2026', title: 'Clearer answers and diagnostics', milestone: 'Rolled back',
    changes: [
      'Comparison and explanation requests keep their full meaning when they also ask for a camera change. Named flights and satellites are handled as questions instead of decorative layer commands.',
      'An optional Diagnostics panel exports a bounded report of timing, model routing, navigation and failures from this tab. Conversation text, audio, images and credentials are excluded.',
      'Unexpected service responses now produce a readable error instead of exposing a JSON parser message.',
    ],
    review: 'Deployment completed, but the live page check exposed import-time diagnostics initialization during server rendering. Production was restored to v0.7.1; v0.8.0 corrects this. Automated checks covered navigation intent, streamed answers, safe errors, telemetry redaction and bounded storage. Live testing of the preceding build exposed the comparison routing failure and dark regional framing. Real flight and satellite tracking, multi-place framing and physical-phone/audio testing remain separate work.',
  },
  {
    version: '0.7.1', date: '2026-09-13', dateLabel: '13 September 2026', title: 'Hosted answers', milestone: 'Previous release',
    changes: ['Repairs a hosted backend startup error by separating local diagnostic files from the online answer service.'],
    review: 'The production-only error was traced from Worker logs to a local file URL in the research module. The fix preserves the answer routes and original globe.',
  },
  {
    version: '0.7.0',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Ask the Earth',
    milestone: 'Previous release',
    changes: [
      'Typed and spoken questions share the original Earth. Geographic answers can travel beyond the three examples, with aerial, horizon and cutaway perspectives.',
      'Everyday questions get a fast answer; harder questions use stronger reasoning or source searches. In-depth research still brings together independent agents. Generated images add context when an illustration helps.',
      'A compact You / Astra conversation replaces the older Explore and fictional-story controls. The globe stays open to visitors; ChatGPT sign-in enables online answers, voice and images.',
    ],
    review: 'TypeScript, build and automated navigation, evidence, streaming, image and hosted-API checks pass. The original globe and typed navigation were checked in a browser. Live API checks cover ordinary questions, source searches and generated images. Hosted microphone/audio and physical-phone performance require separate verification. Geography and movement layers retain their existing source limitations.',
  },
  {
    version: '0.7.1-upstream',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Stay with the place you chose',
    milestone: 'Upstream release',
    changes: [
      'The primary journey button follows the selected destination: regional New York returns to New York city detail, and Challenger Deep returns to the planet.',
      'These actions use the existing world-command path and fast scale transitions. Singapore remains the opening destination.',
    ],
    review: 'Native Mac review confirms New York regional re-entry stays in New York (1.21 seconds), and Challenger Deep returns to planet (1.19 seconds) with Singapore available again. The v0.7 rendering, geography and keyboard controls are unchanged. YC Live conversation remains a separate integration.',
  },
  {
    version: '0.7',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A wider, more responsive world',
    milestone: 'Previous release',
    changes: [
      'Repeated scale changes now travel in 1.1 seconds. Singapore and New York detail prepares after Genesis, and cold journeys begin moving before detail arrives.',
      '72 orbital lights, 120 aircraft and 24 ships occupy distinct heights and routes. Faint violet undersea connections and two distant star shells extend the world around Earth.',
      'Dim, impressionistic city fields continue beyond the mapped Singapore and lower-Manhattan cores. Road traffic follows route length and connectivity; softer activity gathers around junctions.',
      'Focused-canvas navigation adds WASD, Q/E, R/F, T/G, scales 1–4 and reset 0. Text-entry and browser shortcuts remain separate.',
    ],
    review: 'Native Mac WebGL measured warm City to Street and Street to Region at about 1.2 seconds, compared with 6.9 seconds in v0.6.1. Rolling rendering remained near 120 fps in these samples. Source checks cover Genesis endpoints, loading and command settlement, geographic routes, cached continuation and keyboard guards. Movement and surrounding city fields are illustrative, not live tracking or surveyed extensions. Physical-phone performance and the separate YC Live conversation integration remain unverified.',
  },
  {
    version: '0.6.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A clearer view into the deep',
    milestone: 'Previous release',
    changes: [
      'Challenger Deep arrives in the existing angled Horizon view, with clearer seafloor particles at regional scale.',
      'The terrain selector names the active destination. Regional approaches use matching journey language.',
    ],
    review: 'Native WebGL review confirms the angled Mariana view, geographic focus and matching controls. Regional zoom, resizing, perspective switching and the Surface reference pass regression checks. Genesis, planetary exposure and city rendering are unchanged. The v0.6 video remains the recorded living-Earth milestone; YC Live integration is still pending.',
  },
  {
    version: '0.6',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A world born from stars',
    milestone: 'Previous release',
    changes: [
      'A dense nucleus compresses, ignites and ejects its particles into space. The same particles curve home to form geographic Earth.',
      'Sparse icy orbital lights and fast aqua atmospheric trails move above the planet. Subtle surface motion and relief preserve its celestial depth.',
      'Travel through planet, region, city and street scales. Singapore retains its detailed journey; curated lower Manhattan adds a second city in motion.',
      'Warm road traffic follows bundled street geometry, with softer activity around the city. These are deterministic visualisations, not live tracking.',
      'Singapore, New York and Challenger Deep share a small world-command interface prepared for Astra navigation. The manual controls use that same interface.',
    ],
    review: 'Native WebGL reviewed at desktop and phone widths, including the full genesis, paused Earth, destination controls, New York streets and Singapore descent. Automated checks cover immutable geographic endpoints, replay, reduced motion, movement shells, scale changes, geographic highlights, zoom, resizing and graphics interruption. Physical-phone performance remains unverified. Astra coordinated separate renderer, signal and urban engineering tracks; YC owns Live conversation integration, which is not included in this milestone.',
  },
  {
    version: '0.5',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A universe within',
    milestone: 'Previous release',
    changes: [
      'Open the geographic Earth into a layered stellar spiral, then reform the same particles into their original Earth.',
      'Choose three meaningful places from a sourced 48-place catalogue. Their geographic distances shape a constellation of your own.',
      'Return to Earth with your three warm stars and their connections still present: The constellation was us all along.',
      'Personal constellations survive the Singapore journey. Draft reset, change places, clear and full restart have separate meanings.',
      'Both WebGL and the reduced-detail Canvas renderer share the reversible transformation.',
    ],
    review: 'Native WebGL reviewed at desktop and phone widths: opening, three-place entry, warm constellation, closing return, draft reset and a Singapore round trip. Source checks cover immutable home positions, dateline and antipodal cases, repeated reversal and reduced motion. Physical-phone performance remains unverified. Astra coordinated isolated engineering tracks in Codex; no runtime inference is required. The v0.4 prototype and prepared geography predate the hackathon.',
  },
  {
    version: '0.4.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A journey you can return to',
    milestone: 'Previous release',
    changes: [
      'Restart journey returns to the opening Earth with fresh camera, light and story settings.',
      'The home globe fits the desktop composition and adjusts when the window changes size.',
      'Switching between lives preserves the space above the story panel on narrow screens.',
      'A graphics interruption now offers a clear restart instead of dismissing a frozen view.',
    ],
    review: 'Reviewed in native WebGL on a Mac browser, including paused depth views, Singapore, all three lives at phone width, and remembered return. Geography, camera, lifecycle and build checks pass. Phone-width browser review is not physical-phone testing. This sprint continues the pre-existing v0.4 prototype; runtime Astra inference is not part of this release.',
  },
  {
    version: '0.4',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A world with depth',
    milestone: 'Previous release',
    changes: [
      'Real land elevation and ocean-floor relief shape the stars, with exaggerated height to reveal mountains, shelves and trenches.',
      'Layers of stellar matter, soft light and quiet cavities give the world an interior.',
      'Globe, Horizon and Cutaway offer three perspectives on the same Earth. Explore Indonesia and the Java Trench, or the Andes and Pacific.',
      'The Surface reference holds the camera still while you compare the added depth. Pausing motion also holds the shimmer.',
      'The Singapore journey and remembered-life return remain connected to this fuller Earth. Earlier releases are preserved.',
    ],
    review: 'Actual relief data and engine checks pass, including comparison, close zoom and all three lives. Paused desktop and phone-width views were reviewed using the Canvas fallback. Native WebGL appearance and physical-phone performance remain to be reviewed. Interior material is imagined.',
  },
  {
    version: '0.3',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A light you remember',
    milestone: 'Previous release',
    changes: [
      'Independent star rhythms, sharper occasional glints and a fuller glow make the Earth shimmer.',
      'A new Star shimmer control adjusts the effect. Pausing motion keeps the light still.',
      'The last life you visit stays with you after closing its story, gathering into a warm light on the way back to Earth.',
      'The globe settles before the closing words appear. A journey without a visited life has its own neutral return.',
      'Portrait returns allow more room for the remembered light; city point density responds to screen size.',
    ],
    review: 'Source, engine-lifecycle and projected-camera checks cover all three lives, fresh journeys and reduced motion. This release still needs an on-device visual review; earlier fallback screenshots describe v0.2.',
  },
  {
    version: '0.2.1',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A history to build on',
    milestone: 'Saved milestone',
    changes: [
      'A visible version number opens this build history.',
      'Each milestone records its changes and review notes.',
      'The original globe and the v0.2 refinement are preserved as separate snapshots.',
    ],
    review: 'Uses the v0.2 star field. Full WebGL appearance and physical phone performance still need a device review.',
  },
  {
    version: '0.2',
    date: '2026-09-09',
    dateLabel: '9 September 2026',
    title: 'Continuity, light and the human reveal',
    milestone: 'Saved milestone',
    changes: [
      'The camera pulls away from Singapore before turning back toward the globe.',
      'Street detail appears gradually, with quieter light and softer coverage edges.',
      'Choosing a life dims the city, reveals its places and traces their connections.',
      'Stories begin with one sentence and expand on request. Phone framing keeps their places above the panel.',
    ],
    review: 'Camera regression checks and desktop / phone-width fallback checks passed. Saved separately before being included in v0.2.1.',
  },
  {
    version: '0.1',
    date: '2026-09-09',
    dateLabel: '9 September 2026',
    title: 'Earth, constellated',
    milestone: 'Original release',
    changes: [
      'A rotating Earth made from geographic star samples and historical city lights.',
      'A guided descent into central Singapore and three imagined human constellations.',
      'Controls for glow, density, connecting threads and ambient motion.',
    ],
    review: 'Owner screenshots and a recording informed the next pass: city brightness, transition continuity and the human reveal needed work.',
  },
] as const;
